INSERT INTO users (email, is_active, created_at) VALUES
('user1@example.com', TRUE,  now() - interval '30 days'),
('user2@example.com', TRUE,  now() - interval '28 days'),
('user3@example.com', TRUE,  now() - interval '25 days'),
('user4@example.com', TRUE,  now() - interval '22 days'),
('user5@example.com', TRUE,  now() - interval '20 days'),
('user6@example.com', TRUE,  now() - interval '18 days'),
('user7@example.com', FALSE, now() - interval '15 days'),
('user8@example.com', TRUE,  now() - interval '12 days'),
('user9@example.com', TRUE,  now() - interval '10 days'),
('user10@example.com', TRUE, now() - interval '5 days');

INSERT INTO profiles (user_id, full_name, bio, birth_date) VALUES
(1, 'User One',   'Backend developer',      '1995-01-10'),
(2, 'User Two',   'Frontend engineer',      '1996-03-15'),
(3, 'User Three', 'DevOps specialist',      '1994-07-21'),
(4, 'User Four',  'Data analyst',           '1993-11-02'),
(5, 'User Five',  'Product manager',        '1992-05-30'),
(6, 'User Six',   'QA engineer',            '1997-09-12');

INSERT INTO posts (user_id, title, content, created_at) VALUES
(1, 'Post 1',  'Content 1',  now() - interval '20 days'),
(1, 'Post 2',  'Content 2',  now() - interval '19 days'),
(2, 'Post 3',  'Content 3',  now() - interval '18 days'),
(2, 'Post 4',  'Content 4',  now() - interval '17 days'),
(3, 'Post 5',  'Content 5',  now() - interval '16 days'),
(3, 'Post 6',  'Content 6',  now() - interval '15 days'),
(4, 'Post 7',  'Content 7',  now() - interval '14 days'),
(4, 'Post 8',  'Content 8',  now() - interval '13 days'),
(5, 'Post 9',  'Content 9',  now() - interval '12 days'),
(5, 'Post 10', 'Content 10', now() - interval '11 days'),
(6, 'Post 11', 'Content 11', now() - interval '10 days'),
(6, 'Post 12', 'Content 12', now() - interval '9 days'),
(7, 'Post 13', 'Content 13', now() - interval '8 days'),
(7, 'Post 14', 'Content 14', now() - interval '7 days'),
(8, 'Post 15', 'Content 15', now() - interval '6 days'),
(8, 'Post 16', 'Content 16', now() - interval '5 days'),
(9, 'Post 17', 'Content 17', now() - interval '4 days'),
(9, 'Post 18', 'Content 18', now() - interval '3 days'),
(10,'Post 19', 'Content 19', now() - interval '2 days'),
(10,'Post 20', 'Content 20', now() - interval '1 day');

INSERT INTO comments (post_id, user_id, content, created_at) VALUES
(1, 2,  'Nice post!',             now() - interval '10 days'),
(1, 3,  'Great work!',             now() - interval '9 days'),
(2, 4,  'Very helpful.',           now() - interval '8 days'),
(3, 1,  'Interesting.',            now() - interval '7 days'),
(3, 5,  'Thanks for sharing.',     now() - interval '6 days'),
(4, 6,  'Good read.',              now() - interval '5 days'),
(5, 2,  'Awesome!',                now() - interval '4 days'),
(5, 7,  'Well written.',           now() - interval '3 days'),
(6, 8,  'Insightful.',             now() - interval '2 days'),
(7, 9,  'Nice explanation.',       now() - interval '1 day'),
(8, 10, 'Clear and concise.',      now()),
(9, 1,  'Good perspective.',       now()),
(10,2,  'I agree.',                now()),
(11,3,  'Helpful content.',        now()),
(12,4,  'Keep posting!',           now()),
(13,5,  'Valuable info.',          now()),
(14,6,  'Loved it.',               now()),
(15,7,  'Very detailed.',          now()),
(16,8,  'Nice insights.',          now()),
(17,9,  'Good job.',               now()),
(18,10, 'Excellent.',              now()),
(19,1,  'Interesting take.',       now()),
(20,2,  'Well structured.',        now()),
(2, 3,  'Second comment.',         now()),
(4, 5,  'Another feedback.',       now());
